// <auto-generated />
using System;
using MarsRover.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MarsRover.API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MarsRover.API.Models.MarsGrid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("GridName")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("GridSizeX")
                        .HasColumnType("int");

                    b.Property<int>("GridSizeY")
                        .HasColumnType("int");

                    b.Property<int>("GridTotalSize")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfRovers")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Grid");
                });

            modelBuilder.Entity("MarsRover.API.Models.Rover", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("GridId")
                        .HasColumnType("int");

                    b.Property<int?>("MarsGridId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<int>("TotalDeployments")
                        .HasColumnType("int");

                    b.Property<int>("TotalMovements")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MarsGridId");

                    b.ToTable("Rover");
                });

            modelBuilder.Entity("MarsRover.API.Models.RoverMovement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BeginOrientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BeginX")
                        .HasColumnType("int");

                    b.Property<int>("BeginY")
                        .HasColumnType("int");

                    b.Property<string>("EndOrientation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EndX")
                        .HasColumnType("int");

                    b.Property<int?>("EndY")
                        .HasColumnType("int");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("MovementInput")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoverId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoverId");

                    b.ToTable("RoverMovement");
                });

            modelBuilder.Entity("MarsRover.API.Models.Rover", b =>
                {
                    b.HasOne("MarsRover.API.Models.MarsGrid", "MarsGrid")
                        .WithMany("Rovers")
                        .HasForeignKey("MarsGridId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("MarsRover.API.Models.RoverMovement", b =>
                {
                    b.HasOne("MarsRover.API.Models.Rover", "Rover")
                        .WithMany("Movements")
                        .HasForeignKey("RoverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
